### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cormullion** [LiorSinai/PolygonAlgorithms.jl#2]
Hi! This looks great, I will try to see how I can integrate it into Luxor.jl, because some of the polygon functions there are quite rudimentary. If I can do it correctly, I hope to be able to add this repo as a dependency; otherwise, I'll be borrowing some of your code... :) 

Thanks!

**Comment by LiorSinai** [comment]
Sure, happy to help

**Comment by cormullion** [comment]
It's working well!

![polygon_intersection_test_2](https://github.com/LiorSinai/PolygonAlgorithms.jl/assets/52289/9b437205-38bc-4f74-bc27-260b3e52449e)

**Comment by LiorSinai** [comment]
Great. The test cases are very comprehensive and have some tricky scenarios, so it should be easily able to handle all those cases. Here are some of them:

![image](https://github.com/LiorSinai/PolygonAlgorithms.jl/assets/40150322/2ae3140f-d50f-41a9-844a-2a10fafabc13)

The algorithm can't handle self-intersecting algorithms but otherwise it covers nearly every case I have thought of.

If you are interested, I recently wrote an article about this: https://liorsinai.github.io/mathematics/2023/09/30/polygon-clipping.html.
